baseURL = "https://lqgl.cool"
title = "Kami's Planet"
staticDir = ["static", "content-static"]
relativeURLs = true
languageCode = "zh-CN"
defaultContentLanguage = 'zh'
hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
code_copy_button = true # Turn on/off the code-copy-button for code-fields
[author]
  name = "Kami"

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    noClasses = false

  # [markup.blackFriday]
  #   hrefTargetBlank = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 02"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Kami的个人博客"
  keywords = "Kami,blog,博客,个人网站,中文独立博客"
  accentColor = "#54BAB9"
  images = ["apple-touch-icon.png"]
  # bgImg = "/img/bg.jpg"
  # gitUrl = "https://github.com/lqgl/blog/commit/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/kami2077"

  [[params.social]]
    name = "telegram"
    url = "http://t.me/kami2049"

  [[params.social]]
    name = "github"
    url = "https://github.com/lqgl"

[menu]

  [[menu.main]]
    name = "Writing"
    url = "/writing"
    weight = 10

  [[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 20

  [[menu.main]]
    name = "Link"
    url = "/link"
    weight = 30

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 40
